In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 'jupy.py',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [11]:
import pandas as pd
df = pd.read_csv("supermarkets.csv")

In [13]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [33]:
df["Address"] = df["Address"] + " " + df["City"] + " " + df["State"] + " " + df["Country"]
df

ID                                            Address           City  \
0   1  3666 21st St San Francisco CA 94114 USA San Fr...  San Francisco   
1   2  735 Dolores St San Francisco CA 94119 USA San ...  San Francisco   
2   3  332 Hill St San Francisco California 94114 USA...  San Francisco   
3   4  3995 23rd St San Francisco CA 94114 USA San Fr...  San Francisco   
4   5  1056 Sanchez St San Francisco California USA S...  San Francisco   
5   6  551 Alvarado St San Francisco CA 94114 USA San...  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [36]:
import pandas as pd
df = pd.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [38]:
df["Address"] = df["Address"] + ", " + df["City"] + ", " + df["State"] + ", " + df["Country"]
df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [39]:
from geopy.geocoders import ArcGIS

In [40]:
nom = ArcGIS()

In [42]:
df["Coordinates"] = df["Address"].apply(nom.geocode)

In [44]:
df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [47]:
df["Lattitude"] = df["Coordinates"].apply(lambda x : x.latitude)
df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  Lattitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632  
1  (735 Dolores St, San Francisco, California, 94...  37.757829  
2  (332 Hill St, San Francisco, California, 94114...  37.755845  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582

In [49]:
df["Longitude"] = df["Coordinates"].apply(lambda x : x.longitude)
df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  Lattitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

In [51]:
import numpy

In [52]:
n = numpy.arange(21)

In [54]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [55]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [56]:
type(n)

numpy.ndarray

In [60]:
n2 = numpy.range(21)

AttributeError: module 'numpy' has no attribute 'range'

In [61]:
import numpy
n = numpy.arange(21)

In [63]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [65]:
n.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [67]:
import cv2

In [78]:
im_g = cv2.imread("smallgray.png", 1)


In [76]:
import os
os.listdir()

['.ipynb_checkpoints',
 'jupy.py',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [80]:
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [81]:
cv2.imwrite("smallimage.png", im_g)

True